name: android-build
on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.24.3"
          channel: stable

      - name: Flutter pub get
        run: flutter pub get

      - name: Generate Hive adapters
        run: flutter pub run build_runner build --delete-conflicting-outputs
        continue-on-error: true

      - name: Android debug APK
        run: flutter build apk --debug

      - name: Decode keystore
        if: ${{ secrets.KEYSTORE_BASE64 != '' }}
        run: |
          echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 -d > android/app/release.keystore

      - name: Configure signing (Gradle)
        if: ${{ secrets.KEYSTORE_BASE64 != '' }}
        run: |
          cat >> android/key.properties << 'EOF'
          storeFile=release.keystore
          storePassword=${{ secrets.KEYSTORE_PASSWORD }}
          keyPassword=${{ secrets.KEY_PASSWORD }}
          keyAlias=${{ secrets.KEY_ALIAS }}
          EOF

      - name: Release AAB
        if: ${{ secrets.KEYSTORE_BASE64 != '' }}
        run: flutter build appbundle --release

      - name: Release APK (optional)
        if: ${{ secrets.KEYSTORE_BASE64 != '' }}
        run: flutter build apk --release

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: android_builds
          path: |
            build/app/outputs/flutter-apk/*.apk
            build/app/outputs/bundle/release/*.aab