name: Flutter Android APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  FLUTTER_VERSION: '3.24.3'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: stable
          cache: true

      - name: Verify Flutter version
        run: flutter --version

      # إنشاء مشروع Flutter أساسي في حال لم يكن موجودًا
      - name: Create Flutter project if missing
        run: |
          if [ ! -f "pubspec.yaml" ]; then
            flutter create -t app .
          fi

      - name: Flutter Pub Get
        run: flutter pub get

      - name: Analyze
        run: flutter analyze

      - name: Build APK (release)
        run: flutter build apk --release

      - name: List APKs
        run: find build -type f -name "*.apk" -maxdepth 10

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: build/**/*.apk