name: Flutter Android APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  FLUTTER_VERSION: '3.24.3'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Setup Flutter
        id: flutter_setup
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: stable
          cache: true

      - name: Verify Flutter version
        run: flutter --version

      - name: Flutter Pub Get
        run: flutter pub get

      - name: Analyze
        run: flutter analyze

      # بناء APK إصدار نهائي
      - name: Build APK (release)
        run: flutter build apk --release

      # فحص جميع المجلدات لاكتشاف المسار الفعلي
      - name: List outputs
        run: |
          echo "== List build output files =="
          find build -type f -name "*.apk" -maxdepth 10

      # رفع أي ملف APK أينما كان داخل build/
      - name: Upload APK Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: app-apk-files
          path: |
            build/**/*.apk
          if-no-files-found: error