name: Flutter Android APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  FLUTTER_VERSION: '3.24.3'   # إصدار مثبت ومجرب

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      # محاولة أولى بإصدار Flutter مثبت
      - name: Setup Flutter (pinned)
        id: flutter_pinned
        continue-on-error: true
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: stable
          cache: true

      # خطة بديلة: قناة stable فقط
      - name: Fallback to stable channel
        if: steps.flutter_pinned.outcome == 'failure'
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true

      - name: Verify Flutter version
        run: flutter --version

      - name: Flutter Pub Get
        run: flutter pub get

      - name: Analyze
        run: flutter analyze

      # بناء الإصدار النهائي
      - name: Build APK (release)
        id: build_release
        continue-on-error: true
        run: flutter build apk --release

      # إذا فشل الإصدار النهائي، جرّب debug لضمان وجود مخرجات
      - name: Build APK (debug fallback)
        if: steps.build_release.outcome == 'failure'
        run: flutter build apk --debug

      # استكشاف المجلدات لتحديد المسارات الفعلية
      - name: List outputs
        run: |
          echo "== Tree build/app/outputs =="
          ls -R build/app/outputs || true
          echo "== Find APKs =="
          find build -type f -name "*.apk" -maxdepth 8 || true

      # رفع أي ملف APK موجود (release أو debug وأي flavor/ABI)
      - name: Upload APK Artifact(s)
        uses: actions/upload-artifact@v4
        with:
          name: apk-artifacts
          path: |
            build/app/outputs/flutter-apk/*.apk
            build/app/outputs/**/**/*.apk
          if-no-files-found: error