name: Flutter Android APK

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  FLUTTER_VERSION: '3.24.3'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: stable
          cache: true

      - name: Verify Flutter version
        run: |
          flutter --version
          flutter doctor -v

      - name: Create fresh Flutter project
        run: |
          rm -rf new_app
          flutter create -t app new_app

      - name: Replace Dart source
        run: |
          rm -rf new_app/lib
          mkdir -p new_app/lib
          cp -r lib/* new_app/lib/ || true
          cp pubspec.yaml new_app/ || true

      - name: Fix Android build configuration
        run: |
          cd new_app/android
          echo "sdk.dir=/usr/local/android-sdk" > local.properties
          chmod +x gradlew
          cd ../..

      - name: Fix Gradle app module
        run: |
          cat > new_app/android/app/build.gradle <<'EOF'
          def localProperties = new Properties()
          def localPropertiesFile = rootProject.file('local.properties')
          if (localPropertiesFile.exists()) {
              localPropertiesFile.withReader('UTF-8') { reader -> localProperties.load(reader) }
          }
          def flutterRoot = localProperties.getProperty('flutter.sdk')
          if (flutterRoot == null) { throw new GradleException("Flutter SDK not found. Define flutter.sdk in local.properties") }
          plugins { id 'com.android.application'; id 'kotlin-android' }
          apply from: "$flutterRoot/packages/flutter_tools/gradle/flutter.gradle"
          android {
              compileSdkVersion 34
              namespace "com.example.catbook"
              defaultConfig { applicationId "com.example.catbook"; minSdkVersion 21; targetSdkVersion 34; versionCode 1; versionName "1.0" }
              buildTypes { release { signingConfig signingConfigs.debug; minifyEnabled false; shrinkResources false } }
          }
          flutter { source '../..' }
          dependencies { implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:1.9.22" }
          EOF

      - name: Patch Gradle core files
        run: |
          cat > new_app/android/gradle.properties <<'EOF'
          org.gradle.jvmargs=-Xmx2g -XX:+UseParallelGC
          android.useAndroidX=true
          android.enableJetifier=true
          EOF
          cat > new_app/android/settings.gradle <<'EOF'
          pluginManagement {
            repositories { google(); mavenCentral() }
            plugins {
              id("com.android.application") version "8.3.0"
              id("org.jetbrains.kotlin.android") version "1.9.22"
            }
          }
          dependencyResolutionManagement {
            repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
            repositories { google(); mavenCentral() }
          }
          rootProject.name = "catbook"
          include(":app")
          EOF
          mkdir -p new_app/android/gradle/wrapper
          cat > new_app/android/gradle/wrapper/gradle-wrapper.properties <<'EOF'
          distributionBase=GRADLE_USER_HOME
          distributionPath=wrapper/dists
          zipStoreBase=GRADLE_USER_HOME
          zipStorePath=wrapper/dists
          distributionUrl=https\://services.gradle.org/distributions/gradle-8.6-bin.zip
          EOF

      - name: Patch Android root build.gradle
        run: |
          cat > new_app/android/build.gradle <<'EOF'
          buildscript {
            repositories { google(); mavenCentral() }
            dependencies {
              classpath 'com.android.tools.build:gradle:8.3.0'
              classpath 'org.jetbrains.kotlin:kotlin-gradle-plugin:1.9.22'
            }
          }
          allprojects { repositories { google(); mavenCentral() } }
          rootProject.buildDir = '../build'
          subprojects { project.buildDir = "${rootProject.buildDir}/${project.name}" }
          EOF

      - name: Ensure Gradle wrapper is executable
        run: chmod +x new_app/android/gradlew

      - name: Add image assets
        run: |
          mkdir -p new_app/assets/images
          curl -L https://placekitten.com/400/400 -o new_app/assets/images/cat_default.png

      - name: Get dependencies
        working-directory: new_app
        run: flutter pub get

      - name: Analyze (non-blocking)
        working-directory: new_app
        continue-on-error: true
        run: flutter analyze

      - name: Clean project before build
        working-directory: new_app
        run: |
          flutter clean
          flutter pub get

      - name: Build APK (release)
        working-directory: new_app
        id: build_release
        continue-on-error: true
        run: flutter build apk --release -v

      - name: Gradle assemble hard fallback
        if: steps.build_release.outcome == 'failure'
        working-directory: new_app/android
        continue-on-error: true
        run: ./gradlew assembleRelease --stacktrace --info

      - name: Build APK (debug) final fallback
        if: steps.build_release.outcome == 'failure'
        working-directory: new_app
        continue-on-error: true
        run: flutter build apk --debug -v

      - name: Gradle assembleDebug fallback
        if: steps.build_release.outcome == 'failure'
        working-directory: new_app/android
        continue-on-error: true
        run: ./gradlew assembleDebug --stacktrace --info

      - name: Build AAB (Play Store)
        working-directory: new_app
        continue-on-error: true
        run: flutter build appbundle --release -v

      - name: Debug artifact paths
        if: always()
        run: |
          echo "=== SEARCHING FOR APK/AAB FILES ==="
          find new_app -type f \( -name "*.apk" -o -name "*.aab" \) -printf "%p\n" || true
          echo "=== SHOW OUTPUT DIRS ==="
          ls -R new_app/build/app/outputs || true
          ls -R new_app/build/app/intermediates || true
          ls -R new_app/android/app/build/outputs || true

      - name: Collect artifacts to dist
        if: always()
        run: |
          mkdir -p new_app/dist
          find new_app -type f -name "*.apk" -exec cp -v {} new_app/dist/ \; || true
          find new_app -type f -name "*.aab" -exec cp -v {} new_app/dist/ \; || true
          ls -l new_app/dist || true

      - name: Upload APKs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: catbook-apk
          path: new_app/dist/*.apk
          if-no-files-found: warn

      - name: Upload AABs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: catbook-aab
          path: new_app/dist/*.aab
          if-no-files-found: warn