name: Flutter Android APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  FLUTTER_VERSION: '3.24.3'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: stable
          cache: true

      - name: Verify Flutter version
        run: flutter --version

      # إنشاء مشروع Flutter نظيف
      - name: Create fresh Flutter project
        run: |
          rm -rf new_app
          flutter create -t app new_app

      # نسخ كودك إلى المشروع الجديد
      - name: Replace Dart source
        run: |
          rm -rf new_app/lib
          mkdir -p new_app/lib
          cp -r lib/* new_app/lib/ || true