name: Flutter Android APK

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  FLUTTER_VERSION: '3.24.3'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: stable
          cache: true

      - name: Verify Flutter version
        run: flutter --version

      - name: Create fresh Flutter project
        run: |
          rm -rf new_app
          flutter create -t app new_app

      - name: Replace Dart source
        run: |
          rm -rf new_app/lib
          mkdir -p new_app/lib
          cp -r lib/* new_app/lib/ || true
          cp pubspec.yaml new_app/ || true

      - name: Add image assets
        run: |
          mkdir -p new_app/assets/images
          curl -L https://placekitten.com/400/400 -o new_app/assets/images/cat_default.png
          echo "Added cat_default.png"

      - name: Get dependencies
        working-directory: new_app
        run: flutter pub get

      - name: Analyze (non-blocking)
        working-directory: new_app
        continue-on-error: true
        run: flutter analyze

      - name: Build APK (release)
        working-directory: new_app
        id: build_release
        continue-on-error: true
        run: flutter build apk --release

      - name: Build APK (debug fallback)
        if: steps.build_release.outcome == 'failure'
        working-directory: new_app
        run: flutter build apk --debug

      - name: List APKs
        working-directory: new_app
        run: find build -type f -name "*.apk" -maxdepth 10

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: catbook-apk
          path: new_app/build/app/outputs/flutter-apk/app-release.apk
          if-no-files-found: error