name: Flutter Android APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  FLUTTER_VERSION: '3.24.3'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: stable
          cache: true

      - name: Verify Flutter
        run: flutter --version

      # أنشئ مشروع Flutter إن لم توجد pubspec.yaml
      - name: Ensure Flutter project
        run: |
          if [ ! -f "pubspec.yaml" ]; then
            flutter create -t app .
          fi

      - name: Pub get
        run: flutter pub get

      # لا تجعل التحليلات توقف البناء
      - name: Analyze (non-blocking)
        continue-on-error: true
        run: flutter analyze

      # بناء release ثم سقوط إلى debug إن فشل
      - name: Build APK (release)
        id: build_release
        continue-on-error: true
        run: flutter build apk --release

      - name: Build APK (debug fallback)
        if: steps.build_release.outcome == 'failure'
        run: flutter build apk --debug

      # اطبع شجرة المخرجات وسجلات Gradle لتشخيص أي فشل
      - name: Inspect outputs and logs
        run: |
          echo "== APK files =="
          find build -type f -name "*.apk" -maxdepth 10 || true
          echo "== Gradle logs =="
          ls -R android/app/build || true
          ls -R android/build || true

      - name: Upload APK artifacts
        uses: actions/upload-artifact@v4
        with:
          name: app-apk-files
          path: build/**/*.apk
          if-no-files-found: error