name: one-shot-generate-keystore
on:
  workflow_dispatch:

jobs:
  gen:
    runs-on: ubuntu-latest
    steps:
      - name: Generate keystore
        run: |
          keytool -genkeypair -v -keystore release.keystore -storepass ${{ secrets.KEYSTORE_PASSWORD || 'pass12345' }} \
            -keypass ${{ secrets.KEY_PASSWORD || 'pass12345' }} -alias ${{ secrets.KEY_ALIAS || 'catbook' }} \
            -dname "CN=catbook,O=catbook,L=IST,ST=TR,C=TR" -keyalg RSA -keysize 2048 -validity 36500
          echo "BASE64_START"
          base64 -w 0 release.keystore
          echo ""
          echo "BASE64_END"
      - name: Upload keystore artifact
        uses: actions/upload-artifact@v4
        with:
          name: release.keystore
          path: release.keystore